/// Notifications module: sending messages via the Telegram Bot API.
///
/// Uses the sendMessage method:
/// - Endpoint: POST https://api.telegram.org/bot{token}/sendMessage
/// - parse_mode: "HTML" — safe with special characters in node URLs (< > & etc.)
///
/// On send error — logs via tracing::error! and returns Err.
/// The daemon does not panic and continues running (handled at the alert level).
use reqwest::Client;
use serde_json::json;
use tracing::{debug, error};

use crate::config::Config;
use crate::error::SentinelError;
use crate::utils;

/// HTTP client for the Telegram Bot API.
///
/// Holds a `reqwest::Client` for connection reuse.
pub struct TelegramClient {
    http: Client,
}

impl TelegramClient {
    /// Creates a new client. Call once at application startup.
    pub fn new() -> Self {
        Self {
            http: Client::new(),
        }
    }

    /// Sends a text message to the Telegram chat specified in the configuration.
    ///
    /// # Arguments
    /// * `text` — message text (already generated by the LLM)
    /// * `cfg`  — configuration: bot token, chat_id
    ///
    /// # Errors
    /// - `SentinelError::Http`     — network error or timeout
    /// - `SentinelError::Telegram` — Telegram API returned `ok: false`
    pub async fn send_message(&self, text: &str, cfg: &Config) -> Result<(), SentinelError> {
        let url = format!(
            "https://api.telegram.org/bot{}/sendMessage",
            cfg.telegram_bot_token
        );

        let body = json!({
            "chat_id": cfg.telegram_chat_id,
            "text": text,
            // HTML allows <b>, <i> tags and handles special characters in node URLs
            // without additional escaping
            "parse_mode": "HTML"
        });

        debug!(chat_id = cfg.telegram_chat_id, "sending message to Telegram");

        let http = self.http.clone();

        let response: serde_json::Value = utils::retry_async("telegram api", 3, || {
            let http = http.clone();
            let url = url.clone();
            let b = body.clone();
            async move {
                http.post(url)
                    .json(&b)
                    .send()
                    .await
                    .map_err(SentinelError::Http)?
                    .json::<serde_json::Value>()
                    .await
                    .map_err(SentinelError::Http)
            }
        })
        .await?;

        // Telegram returns {"ok": true, ...} on success
        // or {"ok": false, "description": "..."} on error
        if response["ok"].as_bool() != Some(true) {
            let description = response["description"]
                .as_str()
                .unwrap_or("unknown error")
                .to_string();
            error!(chat_id = cfg.telegram_chat_id, error = description, "failed to send Telegram message");
            return Err(SentinelError::Telegram(description));
        }

        debug!("message sent successfully");

        Ok(())
    }
}

// ============================================================================
// Tests
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;
    use std::time::Duration;

    /// Live integration test: real Telegram send.
    /// Run with: cargo test telegram_live -- --ignored --nocapture
    #[tokio::test]
    #[ignore]
    async fn test_telegram_live() {
        dotenvy::dotenv().ok();

        let cfg = Config {
            target_rpc_url: "http://localhost:8899".to_string(),
            reference_rpc_url: "https://api.mainnet-beta.solana.com".to_string(),
            poll_interval: Duration::from_secs(10),
            slot_lag_threshold: 5,
            rtt_threshold_ms: 500,
            alert_cooldown: Duration::from_secs(300),
            mistral_api_key: "placeholder".to_string(),
            mistral_model: "mistral-small-latest".to_string(),
            telegram_bot_token: std::env::var("TELEGRAM_BOT_TOKEN")
                .expect("TELEGRAM_BOT_TOKEN не задан"),
            telegram_chat_id: std::env::var("TELEGRAM_CHAT_ID")
                .expect("TELEGRAM_CHAT_ID не задан"),
        };

        let client = TelegramClient::new();
        client
            .send_message("Тест solana-cli-sentinel: Telegram-клиент работает.", &cfg)
            .await
            .expect("Ошибка отправки в Telegram");

        println!("Сообщение отправлено успешно");
    }
}
